name: Actions CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    name: Check phpBB Extension Member Avatar & Status [MAS]
    runs-on: ubuntu-latest

    steps:

    - name: Actions Checkout
      env:
        EXTNAME: dark1/memberavatarstatus   # CHANGE name of the extension HERE
        PHPBB_BRANCH: 3.2.x                 # phpBB Branch
        SNIFF: 1                            # Should we run code sniffer on your code?
        EPV: 1                              # Should we run EPV (Extension Pre Validator) on your code?
      uses: actions/checkout@v1

    - name: Actions Setup
      run: |
          mkdir --parents ../tmp
          cp -R . ../tmp
          git clone --depth=1 git://github.com/phpbb/phpbb.git phpBB3 --branch=$PHPBB_BRANCH
          cd phpBB3/phpBB
          composer install --no-interaction --no-progress --no-suggest --ignore-platform-reqs
          composer remove sami/sami --no-interaction --no-progress --ignore-platform-reqs --dev
          composer require phpbb/epv:dev-master --no-interaction --no-progress --no-suggest --ignore-platform-reqs --dev
          cd ../../
          mkdir --parents phpBB3/phpBB/ext/$EXTNAME/$EXTNAME
          cp -R ../tmp/* phpBB3/phpBB/ext/$EXTNAME/$EXTNAME

    - name: Actions Test
      run: |
          cd phpBB3
          sh -c "if [ '$SNIFF' != '0' ]; then phpBB/vendor/bin/phpcs -s --extensions=php --standard=build/code_sniffer/ruleset-php-extensions.xml "--ignore=phpBB/ext/$EXTNAME/tests/*" "--ignore=phpBB/ext/$EXTNAME/vendor/*" "phpBB/ext/$EXTNAME"; fi"
          sh -c "if [ '$EPV' != '0' ]; then phpBB/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME' --debug; fi"
